Dev 1.7.x fixing validator issues
cardinity/cardinity-prestashop pull request #18
Opened 2023-03-16 09:11 UTC by shababcardinity

2023-03-16 11:10 UTC, shababcardinity commented
primary change

added php-cs-fixer as a tool, other files mainly changed space line ending etcs form php-cs-fixer

2023-03-17 08:28 UTC, arturasfio requested changes

2023-03-17 08:28 UTC, arturasfio commented on .php-cs-fixer.cache
Cache files should be excluded using `.gitignore`

2023-03-17 08:28 UTC, arturasfio commented on tools/php-cs-fixer/composer.json
Do we need to commit the whole php-cs-fixer into our repository? Every user of our module will have to download this as well, which is definitely not necessary

2023-03-17 09:39 UTC, shababcardinity commented on tools/php-cs-fixer/composer.json
It will not be included in the module, just the repository, tools folder added to be excluded on make which creates the installer.

2023-03-17 09:40 UTC, shababcardinity commented on .php-cs-fixer.cache
added to gitignore and export-ignore

2023-03-17 10:01 UTC, arturasfio commented on .php-cs-fixer.cache
I see the files are added to `.gitignore`, but the files are not removed from repository. Please also remove ignored files from the repository. Also check if there are any other files that are not really required to have in the repository.

2023-03-17 10:03 UTC, arturasfio commented on tools/php-cs-fixer/composer.json
I still do not see any need to have the `php-cs-fixer` added to our repo. This PR is ~1.1k files, and most of them are of `php-cs-fixer`, which is not really relevant in this app context. `php-cs-fixer` could just be installed locally using `composer` and not be commited to the repository.

2023-03-17 10:08 UTC, shababcardinity commented on tools/php-cs-fixer/composer.json
ok, i think i will just remove the vendor of php-cs-fixer and keep the installer composer.json and other files that should help reduce.

2023-03-17 10:13 UTC, shababcardinity commented on tools/php-cs-fixer/composer.json
other than the cache, i already removed files that i thought are no longer in use.

2023-03-17 12:44 UTC, shababcardinity commented on views/img/card.png
no changes in images, not sure if line ending affects them.

2023-03-17 13:03 UTC, arturasfio commented on views/img/card.png
For me, images open normally in `master` branch, but do not open in this branch (image viewers show the image as corrupted). Please confirm that the images were not changed and open correctly in your environment.

2023-03-20 04:46 UTC, shababcardinity commented on views/img/card.png
Same for me, opens locally but cannot view in git branch. I tried to download these corrupted images from master branch to overwrite locally did not work.
![image](https://user-images.githubusercontent.com/72551102/226246815-70cfb7a9-3b48-44d0-b072-92856d522e0e.png)

One issue i noticed when i added the file changes it rewrite crlf line ending to lf even on the iamges, could that be a reason?

2023-03-20 04:55 UTC, shababcardinity commented on views/img/card.png
i think it fixed now, it was problem with git attribute forcing lf to all files not just text

2023-03-20 08:02 UTC, arturasfio approved these changes

2023-03-20 08:37 UTC, merged